#!/usr/bin/env fish

# Get the providers
set provider (s --list-providers | tofi --fuzzy-match true)

# Get the query
set query (cat /dev/null | tofi)

# Perform search
s -p "$provider" "$query"

hyprctl dispatch focusurgentorlast
