#!/usr/bin/env fish

# Get the providers
set provider (s --list-providers | tofi --fuzzy-match true)

if test -n "$provider"

    # Get the query
    set query (cat /dev/null | tofi)

    if test -n "$query"

        # Perform search
        s -p "$provider" "$query"

        hyprctl dispatch focusurgentorlast

    end

end
