#!/bin/bash

echo "### Void linux"
doas xbps-install -Su

echo "### Rust toolchain"
rustup self update

echo "### Rustup tooling"
rustup update

echo "### Cargo packages"
cargo install-update --all

echo "### Bun update"
bun upgrade

echo "### Deno update"
deno upgrade

echo "### Flatpaks update"
flatpak update
