theme = "adwaita-dark"

[editor]
shell = ["fish", "-C"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

#[editor.indent-guides]
#render = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "file-modification-indicator",
]
