[language-server.tinymist]
command = "tinymist"

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "typst"
language-servers = ["tinymist", "harper-ls"]

[[language]]
name = "markdown"
language-servers = ["marksman", "markdown-oxide", "harper-ls"]

[[language]]
name = "python"
language-servers = ["ruff"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings]
lineLength = 80

[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
